"""agregar descripcion a tareas

Revision ID: 5758d9621eeb
Revises: 960c675cb739
Create Date: 2026-08-28 21:17:18.439561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5758d9621eeb'
down_revision: Union[str, Sequence[str], None] = '960c675cb739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas', sa.Column('descripcion', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tareas', 'descripcion')
    # ### end Alembic commands ###

    
